component: aws-iam-role
org: corentindelannoy2
app: asmat-companion
name: express-lambda-permissions

inputs:
  name: ${name}-${stage}
  region: eu-west-1
  service: lambda.amazonaws.com
  policy:
  - Effect: Allow
    Action:
    - sts:AssumeRole
    - logs:CreateLogGroup
    - logs:CreateLogStream
    - logs:PutLogEvents
    Resource: "*"
  - Effect: Allow
    Action:
    - ssm:GetParametersByPath
    Resource: arn:aws:ssm:eu-west-1:613464502594:parameter/asmatcompanion/${stage}
