component: express
org: corentindelannoy2
app: asmat-companion
name: api

inputs:
  region: eu-west-1
  env:
    EXPRESS_COGNITO_USER_POOL_ID: ${output:asmat-companion:cognito-user-pool.UserPoolId}
  src:
    src: ./
    hook: yarn build
    dist: build
  roleName: ${output:asmat-companion:express-lambda-permissions.name}
